### ISSUE TITLE
Broken template for MultiField

### ISSUE THREAD

**Issue by koutoftimer** [maraujop/django-crispy-forms#515] opened 2015-09-22 07:20 UTC
In version 1.4.0 we have following templates constants
https://github.com/maraujop/django-crispy-forms/blob/1.4.0/crispy_forms/layout.py#L286
In version 1.5.2 they have been changed into following
https://github.com/maraujop/django-crispy-forms/blob/1.5.2/crispy_forms/layout.py#L300
But template `<template_package>/multifield.html` for `bootstrap/bootstrap3` is not present in repository in version 1.5.2
https://github.com/maraujop/django-crispy-forms/tree/1.5.2/crispy_forms/templates/bootstrap3

**Comment by carltongibson** [comment] 2015-09-22 08:20
Duplicate of #478. PRs welcome.

**Closed by carltongibson** 2015-09-22 08:20 UTC
