### ISSUE TITLE
String replacement failure when using custom templates 

### ISSUE THREAD

**Issue by tayden** [maraujop/django-crispy-forms#448] opened 2015-07-29 20:12 UTC
If the template kwarg is defined on a Field in a layout, Django1.8 throws a `not all arguments converted during string formatting` error.

This is because in the Field render function (layouts.py line 437), the script attempts to do string replacement on a variable which may no longer have `%s` in the template kwarg that was passed. This makes perfect sense that this string replacement is done on the default template variable `"%s_field.html"`, but I don't think it should be being done when a custom template is passed since users probably aren't defining a custom template/widget for all the available crispy template packs.

**Comment by Remiz** [comment] 2015-08-17 20:12
I noticed the same thing on 1.5.0 with my current project. I only notice it when I use Django form wizard.

**Comment by carltongibson** [comment] 2015-08-17 20:15
Anyone want to give me a failing test case here?

**Comment by Remiz** [comment] 2015-08-17 20:42
I'm working on a small test case right now, my actual form is rather complex so I'm trying to isolate the issue.

**Comment by carltongibson** [comment] 2015-08-17 21:19
@Remiz that's what I like to hear! :-)

**Comment by Remiz** [comment] 2015-08-18 21:45
I narrowed it down to a part where I'm using a custom template for a Field object, as @tayden says...
```python
# In form definition
instant_alerts = forms.MultipleChoiceField(
    choices=CHOICES_ALERT,
    label='Instant alerts on',
    widget=forms.CheckboxSelectMultiple(),
    required=False,
)
...
# In init() self.helper.layout definition
Field(
    'instant_alerts',
    template='common/checkboxselectmultiple.html'
),
...

I kind of fixed my issue by no longer using a custom template for that field, but I'm sure other people may want to have customization working.

**Comment by carltongibson** [comment] 2015-08-19 20:28
This is a duplicate of #361, I now realise. 

Have opened #493 to address. Please review.

**Closed by carltongibson** 2015-08-19 20:28 UTC
Labels: Bug
